---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-oracle
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/u01/app/oracle/oradata/ORCL" 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tomcat8
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/config"
...
