apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-oracle
  namespace: ns-demo
spec: 
  storageClassName: manual
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
