---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tomcat8
  namespace: ns-demo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat8
  namespace: ns-demo
spec:
  selector:
    matchLabels:
      app: hello
      tier: tomcat8
  replicas: 30
  template:
    metadata:
      labels:
        app: hello
        tier: tomcat8
    spec:
      volumes:
      - name: pv-tomcat-storage
        persistentVolumeClaim:
          claimName: pvc-tomcat8

      containers:
        - name: tomcat8
          image: "ousema2003/myrepo:tomcat88"
          ports:
          - containerPort: 8080

          volumeMounts:
          - mountPath: "/opt/config"
            name: pv-tomcat-storage
...
