---
apiVersion: v1
kind: Service
metadata:
  name: frontend-tomcat8-clusterip
  namespace: ns-demo
spec:
  selector:
    app: hello
    tier: tomcat8
  ports:
  - protocol: "TCP"
    port: 9080
    targetPort: 8080
  type: ClusterIP
...
